apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xn32lsb8c-python 
  janus-idp.io/tekton: xn32lsb8c-python
  backstage.io/kubernetes-id: xn32lsb8c-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xn32lsb8c-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml