apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xn32lsb8c-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xn32lsb8c-python 
  name: xn32lsb8c-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xn32lsb8c-python 
